// layouts/components/navbar/index.vue
<template>
  <section class="container">
    <section class="flex flex--justify-space-between flex--align-center py-4">
      <section>
        <nuxt-link class="text--black" to="/">
          <h3>Dwi Nugroho</h3>
        </nuxt-link>
      </section>
      <section class="flex flex--align-center flex--justify-end">
        <section class="navbar-menu flex flex--align-center flex--justify-end">
          <nuxt-link
            v-for="(item, index) in menu"
            :key="index"
            class="navbar-menu__item text--black ml-3"
            :to="item.path"
          >
            <p class="text--weight-500 text--capitalize mb-0">
              {{ item.title }}
            </p>
          </nuxt-link>
        </section>
        <section class="flex flex--align-center flex--justify-end ml-4">
          <a class="text--black ml-3" href="#">
            <svg-icon
              :name="`icons/linkedin`"
              title="linkedin"
              width="20px"
              height="20px"
              class="mb-0"
            />
          </a>
          <a class="text--black ml-3" href="#">
            <svg-icon
              :name="`icons/github`"
              title="linkedin"
              width="20px"
              height="20px"
              class="mb-0"
            />
          </a>
        </section>
      </section>
    </section>
  </section>
</template>

<script>
import Vue from 'vue';

export default Vue.extend({
  name: 'Navbar',
  data: () => ({
    menu: [
      {
        title: 'Articles',
        path: '/articles',
      },
      {
        title: 'About',
        path: '/about',
      },
    ],
  }),
});
</script>

<style lang="scss" scoped>
.navbar-menu {
  @include breakpoint-down(md) {
    display: none;
  }
  &__item {
    padding: 4px 8px 2px 8px;
    border-radius: 4px;
    &:hover {
      background-color: lighten($color: $lighter-black, $amount: 4%);
    }
  }
}

.active-route,
.nuxt-link-active {
  background-color: $lighter-black !important;
}
</style>

// src/components/organisms/navbar/index.tsx
import * as React from 'react';
import { Link } from 'gatsby';
import ReactToolTip from 'react-tooltip';

import Github from '@/assets/icons/github.svg';
import LinkedIn from '@/assets/icons/linkedin.svg';

import './style.scss';

export interface Props {
  //
}

export const Navbar: React.FC<Props> = () => {
  const [isClient, setClient] = React.useState(false);

  React.useEffect(() => {
    setClient(true);
  }, []);

  return (
    <section className="organism-navbar background--white width--100">
      <nav
        className="container flex flex--align-center flex--justify-space-between width--100"
        style={{ minHeight: '84px' }}
      >
        <Link to="/">
          <h3 className="mb-0 text--black">DwiNugroho</h3>
        </Link>
        <section className="component--desktop-visible flex flex--align-center">
          {/* <Link
            to="/"
            className="organism-navbar__item mx-3"
            activeClassName="organism-navbar__item--active"
          >
            <p>Home</p>
          </Link> */}
          <Link
            to="/blog"
            className="organism-navbar__item mx-3"
            activeClassName="organism-navbar__item--active"
          >
            <p>Blog</p>
          </Link>
          {/* <Link
            to="/projects"
            className="organism-navbar__item mx-3"
            activeClassName="organism-navbar__item--active"
          >
            <p>Projects</p>
          </Link> */}
          <Link
            to="/me"
            className="organism-navbar__item mx-3"
            activeClassName="organism-navbar__item--active"
          >
            <p>About Me</p>
          </Link>
        </section>
        <section className="flex flex--align-center">
          <a
            data-tip="LinkedIn"
            href="https://www.linkedin.com/in/dwi-nugroho-462126138/"
            target="_blank"
            className="organism-navbar__item mx-2"
          >
            <LinkedIn />
          </a>
          <a
            data-tip="Github"
            href="https://github.com/DwiNugroho"
            target="_blank"
            className="organism-navbar__item mx-2"
          >
            <Github />
          </a>

          {isClient && <ReactToolTip effect="solid" place="bottom" />}
        </section>
      </nav>
    </section>
  );
};

Navbar.defaultProps = {
  //
};

export default Navbar;
