// layouts/components/navbar/index.vue
<template>
  <section class="container">
    <section class="flex flex--justify-space-between flex--align-center py-4">
      <section>
        <nuxt-link class="text--black" to="/">
          <h3>Dwi Nugroho</h3>
        </nuxt-link>
      </section>
      <section class="flex flex--align-center flex--justify-end">
        <section class="navbar-menu flex flex--align-center flex--justify-end">
          <nuxt-link
            v-for="(item, index) in menu"
            :key="index"
            class="navbar-menu__item text--black ml-3"
            :to="item.path"
          >
            <p class="text--weight-500 text--capitalize mb-0">
              {{ item.title }}
            </p>
          </nuxt-link>
        </section>
        <section class="flex flex--align-center flex--justify-end ml-4">
          <a class="text--black ml-3" href="#">
            <svg-icon
              :name="`icons/linkedin`"
              title="linkedin"
              width="20px"
              height="20px"
              class="mb-0"
            />
          </a>
          <a class="text--black ml-3" href="#">
            <svg-icon
              :name="`icons/github`"
              title="linkedin"
              width="20px"
              height="20px"
              class="mb-0"
            />
          </a>
        </section>
      </section>
    </section>
  </section>
</template>

<script>
import Vue from 'vue';

export default Vue.extend({
  name: 'Navbar',
  data: () => ({
    menu: [
      {
        title: 'Articles',
        path: '/articles',
      },
      {
        title: 'About',
        path: '/about',
      },
    ],
  }),
});
</script>

<style lang="scss" scoped>
.navbar-menu {
  @include breakpoint-down(md) {
    display: none;
  }
  &__item {
    padding: 4px 8px 2px 8px;
    border-radius: 4px;
    &:hover {
      background-color: lighten($color: $lighter-black, $amount: 4%);
    }
  }
}

.active-route,
.nuxt-link-active {
  background-color: $lighter-black !important;
}
</style>

// src/layouts/components/navbar/index.tsx
import React from 'react';
import { useStaticQuery, graphql, Link } from 'gatsby';

import Menu from '@/api/menu';
import Github from '@/assets/icons/github.svg';
import LinkedIn from '@/assets/icons/linkedin.svg';

import './style.scss';

const Navbar = () => {
  const data = useStaticQuery(graphql`
    query SiteTitleQuery {
      site {
        siteMetadata {
          title
        }
      }
    }
  `);

  return (
    <nav className="container navbar">
      <section className="navbar__content">
        <Link to="/" className="navbar__title">
          <h3 className="m-0">{data.site.siteMetadata.title}</h3>
        </Link>
        {Menu.map((item, index) => (
          <Link key={index} to={item.path} className="navbar__menu">
            <p className="m-0">{item.name}</p>
          </Link>
        ))}
      </section>
      <section className="navbar__icons">
        <a
          href="https://www.linkedin.com/in/dwi-nugroho-462126138/"
          rel="noreferrer"
          target="_blank"
        >
          <LinkedIn />
        </a>
        <a
          href="https://github.com/DwiNugroho"
          rel="noreferrer"
          target="_blank"
        >
          <Github />
        </a>
      </section>
    </nav>
  );
};

export default Navbar;
