// layouts/components/footer/index.vue
<template>
  <section class="container">
    <hr />
    <section
      class="footer flex flex--align-center flex--justify-center flex--wrap py-4 mb-5"
    >
      <a
        v-for="(item, index) in menu"
        :key="index"
        href="#"
        class="footer__menu text--black p-2 mx-3 text--center text--weight-500"
      >
        {{ item.title }}
      </a>
    </section>
  </section>
</template>

<script>
import Vue from 'vue';

export default Vue.extend({
  name: 'Navbar',
  data: () => ({
    menu: [
      {
        title: 'Medium',
        link: '#',
      },
      {
        title: 'Github',
        link: '#',
      },
      {
        title: 'Instagram',
        link: '#',
      },
      {
        title: 'LinkedIn',
        link: '#',
      },
    ],
  }),
});
</script>

<style lang="scss" scoped>
.footer {
  &__menu {
    &:hover {
      color: $blue;
    }
  }
}
</style>

// src/components/organisms/footer/index.tsx
import * as React from 'react';

import './style.scss';

export interface Props {
  //
}

export const Navbar: React.FC<Props> = () => {
  return (
    <section className="organism-footer width--100 container flex flex--wrap flex--align-center flex--justify-center my-5 pt-5">
      <a href="" className="organism-footer__item mx-3">
        <p>Medium</p>
      </a>
      <a href="" className="organism-footer__item mx-3">
        <p>Facebook</p>
      </a>
      <a href="" className="organism-footer__item mx-3">
        <p>Instagram</p>
      </a>
      <a href="" className="organism-footer__item mx-3">
        <p>LinkedIn</p>
      </a>
      <a href="" className="organism-footer__item mx-3">
        <p>Github</p>
      </a>
    </section>
  );
};

Navbar.defaultProps = {
  //
};

export default Navbar;
